# 1 jobs
# wandb:
#   group: ft-down

restore_dataloader: false
reset_optimizer_state: true
reset_trainer_state: true
load_path: prior
load_checkpoint_type: unsharded
eval_on_load: true
device_train_microbatch_size: 32
max_duration: 1ep
sft_dataset:
  type: downstream
  sft: true
  sft_use_label: true 
sweep:
  - data: 
      paths: conditional_data
    scheduler:
      t_warmup: 20