# 21 jobs
# wandb:
#   group:  score-parallel

just_score_model: true
max_duration:  60000
global_train_batch_size: 256
device_train_microbatch_size: 256 
restore_dataloader: false # restart from step 0
reset_optimizer_state: true
reset_trainer_state: true
seed: 1
sweep:
  - load_path:
      - prior
      - conditional_books
      - conditional_down
    load_checkpoint_type: unsharded
    data_start_step: # whole dataset in parallel
      - 0
      - 60000


# Expecting ~2.5B tokens/hr